version: "3.9"

services:
  worker:
    # Constrói a imagem a partir do Dockerfile local
    build: .
    # Define um nome para a imagem construída
    image: tjsp-worker:latest
    # Define um nome para o contêiner em execução
    container_name: tjsp_worker_1
    
    # IMPORTANTE: Usa rede host para acessar ChromeDriver local (porta 4444)
    network_mode: host
    
    # Carrega todas as variáveis do arquivo .env
    env_file:
      - .env
    
    # Variáveis de ambiente específicas para Xvfb + ChromeDriver
    environment:
      # ChromeDriver local rodando no host (não mais Selenium Grid)
      - SELENIUM_REMOTE_URL=http://localhost:4444
      # Display virtual do Xvfb
      - DISPLAY=:99

    # Mapeia pastas locais para dentro do contêiner
    volumes:
      - ./downloads:/app/downloads
      - ./screenshots:/app/screenshots
      - ./certs:/app/certs
      # Monta NSS database do host (certificados digitais)
      - /root/.pki/nssdb:/root/.pki/nssdb:ro

    # Reinicia automaticamente em caso de falha
    restart: unless-stopped

  # COMENTADO: Não usamos mais Selenium Grid em container
  # Agora usamos ChromeDriver + Xvfb instalados diretamente no host Ubuntu
  # selenium-chrome:
  #   image: selenium/standalone-chrome:latest
  #   container_name: selenium_chrome
  #   ports:
  #     - "4444:4444"
  #     - "7900:7900"
  #   shm_size: '2gb'
  #   environment:
  #     - SE_NODE_MAX_SESSIONS=5
  #     - SE_NODE_SESSION_TIMEOUT=300
  #   volumes:
  #     - ./downloads:/home/seluser/downloads
  #     - ./screenshots:/home/seluser/screenshots