version: "3.9"

services:
  revisa:
    image: revisa-crawler:latest
    build: .
    container_name: revisa
    ports:
      - "8000:8000"
    volumes:
      - ./downloads:/data/downloads
      - ./certs:/app/certs
    environment:
      - CERT_PASS=903205
      - TZ=America/Sao_Paulo
    shm_size: 1g
    restart: unless-stopped
